### ISSUE TITLE
Hi，Hazem

### ISSUE THREAD

**Issue by zzrsunshine** [hxazem/Image-Forgery-Detection-using-Deep-learning#6]

**Comment by zzrsunshine** [comment]
> Hi，Hazem，Can you send all the files to my Email？Why is there no screen in the interface I run? The input image test did not yield any results, and the code exited the run directly？I hope you can help me answer some questions,I will be immensely grateful！

**Comment by HXM14** [comment]
Ask me your questions , however this was my graduation project 4 yesrs ago
but i will help if i can 😅
